/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dss_vms_jni_interfaces_ProbeMaster */

#ifndef _Included_com_dss_vms_jni_interfaces_ProbeMaster
#define _Included_com_dss_vms_jni_interfaces_ProbeMaster
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dss_vms_jni_interfaces_ProbeMaster
 * Method:    _initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_ProbeMaster__1initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_ProbeMaster
 * Method:    _tearDown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_ProbeMaster__1tearDown
  (JNIEnv *, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_ProbeMaster
 * Method:    _addStream
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_ProbeMaster__1addStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_ProbeMaster
 * Method:    _removeStream
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_ProbeMaster__1removeStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_ProbeMaster
 * Method:    _setRegion
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_ProbeMaster__1setRegion
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_ProbeMaster
 * Method:    _searchEvent
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_ProbeMaster__1searchEvent
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_ProbeMaster
 * Method:    _execute
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_ProbeMaster__1execute
  (JNIEnv *, jobject, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
