################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
LIBRARIES := 
CC_DEPS := 
C++_DEPS := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
dlib-19.17/dlib/all \
dlib-19.17/dlib/base64 \
dlib-19.17/dlib/bigint \
dlib-19.17/dlib/bit_stream \
dlib-19.17/dlib/bsp \
dlib-19.17/dlib/cmake_utils/test_for_avx \
dlib-19.17/dlib/cmake_utils/test_for_cpp11 \
dlib-19.17/dlib/cmake_utils/test_for_neon \
dlib-19.17/dlib/cmake_utils/test_for_sse4 \
dlib-19.17/dlib/cuda \
dlib-19.17/dlib/data_io \
dlib-19.17/dlib/dir_nav \
dlib-19.17/dlib/entropy_decoder \
dlib-19.17/dlib/entropy_encoder \
dlib-19.17/dlib/external/cblas \
dlib-19.17/dlib/external/libjpeg \
dlib-19.17/dlib/external/libpng/arm \
dlib-19.17/dlib/external/libpng \
dlib-19.17/dlib/external/zlib \
dlib-19.17/dlib/filtering \
dlib-19.17/dlib/global_optimization \
dlib-19.17/dlib/gui_core \
dlib-19.17/dlib/gui_widgets \
dlib-19.17/dlib/http_client \
dlib-19.17/dlib/image_loader \
dlib-19.17/dlib/image_saver \
dlib-19.17/dlib/linker \
dlib-19.17/dlib/logger \
dlib-19.17/dlib/matlab \
dlib-19.17/dlib/md5 \
dlib-19.17/dlib/misc_api \
dlib-19.17/dlib/server \
dlib-19.17/dlib/sockets \
dlib-19.17/dlib/sockstreambuf \
dlib-19.17/dlib \
dlib-19.17/dlib/svm \
dlib-19.17/dlib/test \
dlib-19.17/dlib/test/blas_bindings \
dlib-19.17/dlib/test/gui \
dlib-19.17/dlib/threads \
dlib-19.17/dlib/timer \
dlib-19.17/dlib/tokenizer \
dlib-19.17/dlib/unicode \
dlib-19.17/examples \
dlib-19.17/examples/build/CMakeFiles/3.10.2/CompilerIdC \
dlib-19.17/examples/build/CMakeFiles/3.10.2/CompilerIdCXX \
dlib-19.17/examples/build/CMakeFiles/3d_point_cloud_ex.dir \
dlib-19.17/examples/build/CMakeFiles/CheckTypeSize \
dlib-19.17/examples/build/CMakeFiles/assignment_learning_ex.dir \
dlib-19.17/examples/build/CMakeFiles/bayes_net_ex.dir \
dlib-19.17/examples/build/CMakeFiles/bayes_net_from_disk_ex.dir \
dlib-19.17/examples/build/CMakeFiles/bayes_net_gui_ex.dir \
dlib-19.17/examples/build/CMakeFiles/bridge_ex.dir \
dlib-19.17/examples/build/CMakeFiles/bsp_ex.dir \
dlib-19.17/examples/build/CMakeFiles/compress_stream_ex.dir \
dlib-19.17/examples/build/CMakeFiles/config_reader_ex.dir \
dlib-19.17/examples/build/CMakeFiles/custom_trainer_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dir_nav_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_face_recognition_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_imagenet_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_imagenet_train_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_inception_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_introduction2_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_introduction_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_metric_learning_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_metric_learning_on_images_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_mmod_dog_hipsterizer.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_mmod_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_mmod_face_detection_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_mmod_find_cars2_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_mmod_find_cars_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_mmod_train_find_cars_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_semantic_segmentation_ex.dir \
dlib-19.17/examples/build/CMakeFiles/dnn_semantic_segmentation_train_ex.dir \
dlib-19.17/examples/build/CMakeFiles/empirical_kernel_map_ex.dir \
dlib-19.17/examples/build/CMakeFiles/face_detection_ex.dir \
dlib-19.17/examples/build/CMakeFiles/face_landmark_detection_ex.dir \
dlib-19.17/examples/build/CMakeFiles \
dlib-19.17/examples/build/CMakeFiles/fhog_ex.dir \
dlib-19.17/examples/build/CMakeFiles/fhog_object_detector_ex.dir \
dlib-19.17/examples/build/CMakeFiles/file_to_code_ex.dir \
dlib-19.17/examples/build/CMakeFiles/graph_labeling_ex.dir \
dlib-19.17/examples/build/CMakeFiles/gui_api_ex.dir \
dlib-19.17/examples/build/CMakeFiles/hough_transform_ex.dir \
dlib-19.17/examples/build/CMakeFiles/image_ex.dir \
dlib-19.17/examples/build/CMakeFiles/integrate_function_adapt_simp_ex.dir \
dlib-19.17/examples/build/CMakeFiles/iosockstream_ex.dir \
dlib-19.17/examples/build/CMakeFiles/kcentroid_ex.dir \
dlib-19.17/examples/build/CMakeFiles/kkmeans_ex.dir \
dlib-19.17/examples/build/CMakeFiles/krls_ex.dir \
dlib-19.17/examples/build/CMakeFiles/krls_filter_ex.dir \
dlib-19.17/examples/build/CMakeFiles/krr_classification_ex.dir \
dlib-19.17/examples/build/CMakeFiles/krr_regression_ex.dir \
dlib-19.17/examples/build/CMakeFiles/learning_to_track_ex.dir \
dlib-19.17/examples/build/CMakeFiles/least_squares_ex.dir \
dlib-19.17/examples/build/CMakeFiles/linear_manifold_regularizer_ex.dir \
dlib-19.17/examples/build/CMakeFiles/logger_custom_output_ex.dir \
dlib-19.17/examples/build/CMakeFiles/logger_ex.dir \
dlib-19.17/examples/build/CMakeFiles/logger_ex_2.dir \
dlib-19.17/examples/build/CMakeFiles/matrix_ex.dir \
dlib-19.17/examples/build/CMakeFiles/matrix_expressions_ex.dir \
dlib-19.17/examples/build/CMakeFiles/max_cost_assignment_ex.dir \
dlib-19.17/examples/build/CMakeFiles/member_function_pointer_ex.dir \
dlib-19.17/examples/build/CMakeFiles/mlp_ex.dir \
dlib-19.17/examples/build/CMakeFiles/model_selection_ex.dir \
dlib-19.17/examples/build/CMakeFiles/mpc_ex.dir \
dlib-19.17/examples/build/CMakeFiles/multiclass_classification_ex.dir \
dlib-19.17/examples/build/CMakeFiles/multithreaded_object_ex.dir \
dlib-19.17/examples/build/CMakeFiles/object_detector_advanced_ex.dir \
dlib-19.17/examples/build/CMakeFiles/object_detector_ex.dir \
dlib-19.17/examples/build/CMakeFiles/one_class_classifiers_ex.dir \
dlib-19.17/examples/build/CMakeFiles/optimization_ex.dir \
dlib-19.17/examples/build/CMakeFiles/parallel_for_ex.dir \
dlib-19.17/examples/build/CMakeFiles/pipe_ex.dir \
dlib-19.17/examples/build/CMakeFiles/pipe_ex_2.dir \
dlib-19.17/examples/build/CMakeFiles/quantum_computing_ex.dir \
dlib-19.17/examples/build/CMakeFiles/queue_ex.dir \
dlib-19.17/examples/build/CMakeFiles/random_cropper_ex.dir \
dlib-19.17/examples/build/CMakeFiles/rank_features_ex.dir \
dlib-19.17/examples/build/CMakeFiles/running_stats_ex.dir \
dlib-19.17/examples/build/CMakeFiles/rvm_ex.dir \
dlib-19.17/examples/build/CMakeFiles/rvm_regression_ex.dir \
dlib-19.17/examples/build/CMakeFiles/sequence_labeler_ex.dir \
dlib-19.17/examples/build/CMakeFiles/sequence_segmenter_ex.dir \
dlib-19.17/examples/build/CMakeFiles/server_http_ex.dir \
dlib-19.17/examples/build/CMakeFiles/server_iostream_ex.dir \
dlib-19.17/examples/build/CMakeFiles/sockets_ex.dir \
dlib-19.17/examples/build/CMakeFiles/sockstreambuf_ex.dir \
dlib-19.17/examples/build/CMakeFiles/std_allocator_ex.dir \
dlib-19.17/examples/build/CMakeFiles/surf_ex.dir \
dlib-19.17/examples/build/CMakeFiles/svm_c_ex.dir \
dlib-19.17/examples/build/CMakeFiles/svm_ex.dir \
dlib-19.17/examples/build/CMakeFiles/svm_pegasos_ex.dir \
dlib-19.17/examples/build/CMakeFiles/svm_rank_ex.dir \
dlib-19.17/examples/build/CMakeFiles/svm_sparse_ex.dir \
dlib-19.17/examples/build/CMakeFiles/svm_struct_ex.dir \
dlib-19.17/examples/build/CMakeFiles/svr_ex.dir \
dlib-19.17/examples/build/CMakeFiles/thread_function_ex.dir \
dlib-19.17/examples/build/CMakeFiles/thread_pool_ex.dir \
dlib-19.17/examples/build/CMakeFiles/threaded_object_ex.dir \
dlib-19.17/examples/build/CMakeFiles/threads_ex.dir \
dlib-19.17/examples/build/CMakeFiles/timer_ex.dir \
dlib-19.17/examples/build/CMakeFiles/train_object_detector.dir \
dlib-19.17/examples/build/CMakeFiles/train_shape_predictor_ex.dir \
dlib-19.17/examples/build/CMakeFiles/using_custom_kernels_ex.dir \
dlib-19.17/examples/build/CMakeFiles/video_tracking_ex.dir \
dlib-19.17/examples/build/CMakeFiles/webcam_face_pose_ex.dir \
dlib-19.17/examples/build/CMakeFiles/xml_parser_ex.dir \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/base64 \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/bigint \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/bit_stream \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/bsp \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/cuda \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/data_io \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/dir_nav \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/entropy_decoder \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/entropy_encoder \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/filtering \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/global_optimization \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/gui_core \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/gui_widgets \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/image_loader \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/image_saver \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/linker \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/logger \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/md5 \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/misc_api \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/server \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/sockets \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/sockstreambuf \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/svm \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/threads \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/timer \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/tokenizer \
dlib-19.17/examples/build/dlib_build/CMakeFiles/dlib.dir/unicode \
dlib-19.17/tools/archive \
dlib-19.17/tools/convert_dlib_nets_to_caffe \
dlib-19.17/tools/htmlify \
dlib-19.17/tools/htmlify/to_xml_example \
dlib-19.17/tools/imglab/src \
dlib-19.17/tools/python/src \
src \

