/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dss_vms_jni_interfaces_CodecMaster */

#ifndef _Included_com_dss_vms_jni_interfaces_CodecMaster
#define _Included_com_dss_vms_jni_interfaces_CodecMaster
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _tearDown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1tearDown
  (JNIEnv *, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _addDecorder
 * Signature: (Ljava/nio/ByteBuffer;BB)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1addDecorder
  (JNIEnv *, jobject, jobject, jbyte, jbyte);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _removeDecorder
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1removeDecorder
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _decode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1decode__Ljava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _decode
 * Signature: (BBLjava/nio/ByteBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1decode__BBLjava_nio_ByteBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jobject, jbyte, jbyte, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _addEncoder
 * Signature: (Ljava/nio/ByteBuffer;BBIII)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1addEncoder
  (JNIEnv *, jobject, jobject, jbyte, jbyte, jint, jint, jint);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _removeEncoder
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1removeEncoder
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_CodecMaster
 * Method:    _encode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_CodecMaster__1encode
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
