/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dss_vms_jni_interfaces_StreamMaster */

#ifndef _Included_com_dss_vms_jni_interfaces_StreamMaster
#define _Included_com_dss_vms_jni_interfaces_StreamMaster
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dss_vms_jni_interfaces_StreamMaster
 * Method:    _initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_StreamMaster__1initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_StreamMaster
 * Method:    _tearDown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_StreamMaster__1tearDown
  (JNIEnv *, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_StreamMaster
 * Method:    _addStream
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_StreamMaster__1addStream
  (JNIEnv *, jobject, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_dss_vms_jni_interfaces_StreamMaster
 * Method:    _removeStream
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_StreamMaster__1removeStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_StreamMaster
 * Method:    _getContent
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_StreamMaster__1getContent
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_StreamMaster
 * Method:    _pauseStream
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_StreamMaster__1pauseStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dss_vms_jni_interfaces_StreamMaster
 * Method:    _resumeStream
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_dss_vms_jni_interfaces_StreamMaster__1resumeStream
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
